export const products = [
    {
        "id": "sai0001",
        "name": "Esprit Ruffle Shirt",
        "price": 16.64,
        "image": "images/product-01.jpg",
        "category": "women",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Shirt"],
        "colors": ["#717fe0", "#e67e22", "#2ecc71"],
        "sizes": ["S", "M", "L", "XL"]
    },
    {
        "id": "sai0002",
        "name": "Herschel supply",
        "price": 35.31,
        "image": "images/product-02.jpg",
        "category": "bag",
        "description": "This premium bag blends functionality with minimalist design. Perfect for daily use or light travel.",
        "tags": ["Fashion", "Bag"],
        "colors": ["#333333", "#ffffff", "#f1c40f"],
        "sizes": ["One Size"]
    },
    {
        "id": "sai0003",
        "name": "Only Check Trouser",
        "price": 25.50,
        "image": "images/product-03.jpg",
        "category": "men",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Denim"],
        "colors": ["#2c3e50", "#95a5a6"],
        "sizes": ["M", "L", "XL"]
    },
    {
        "id": "sai0004",
        "name": "Classic Trench Coat",
        "price": 75.00,
        "image": "images/product-04.jpg",
        "category": "women",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Coat"],
        "colors": ["#d35400", "#2c3e50"],
        "sizes": ["S", "M", "L"]
    },
    {
        "id": "sai0005",
        "name": "Front Pocket Jumper",
        "price": 34.75,
        "image": "images/product-05.jpg",
        "category": "women",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Jumper"],
        "colors": ["#9b59b6", "#34495e"],
        "sizes": ["S", "M", "L"]
    },
    {
        "id": "sai0006",
        "name": "Vintage Inspired Classic",
        "price": 93.20,
        "image": "images/product-06.jpg",
        "category": "watches",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Watch"],
        "colors": ["#f1c40f", "#bdc3c7"],
        "sizes": ["Adjustable"]
    },
    {
        "id": "sai0007",
        "name": "Shirt in Stretch Cotton",
        "price": 52.66,
        "image": "images/product-07.jpg",
        "category": "women",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Shirt"],
        "colors": ["#ffffff", "#3498db"],
        "sizes": ["S", "M", "L", "XL"]
    },
    {
        "id": "sai0008",
        "name": "Pieces Metallic Printed",
        "price": 18.96,
        "image": "images/product-08.jpg",
        "category": "women",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Qt", "Fashion"],
        "colors": ["#e74c3c", "#f39c12"],
        "sizes": ["S", "M"]
    },
    {
        "id": "sai0009",
        "name": "Converse All Star Hi Plimsolls",
        "price": 75.00,
        "image": "images/product-09.jpg",
        "category": "shoes",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Shoes"],
        "colors": ["#ffffff", "#e74c3c", "#333333"],
        "sizes": ["38", "39", "40", "41", "42"]
    },
    {
        "id": "sai0010",
        "name": "Femme T-Shirt In Stripe",
        "price": 25.85,
        "image": "images/product-10.jpg",
        "category": "women",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Shirt"],
        "colors": ["#3498db", "#bdc3c7"],
        "sizes": ["S", "M", "L"]
    },
    {
        "id": "sai0011",
        "name": "Herschel Travel Backpack",
        "price": 63.16,
        "image": "images/product-11.jpg",
        "category": "bag",
        "description": "A spacious and durable backpack for all your travel needs. Featuring multiple compartments and ergonomic straps.",
        "tags": ["Fashion", "Bag"],
        "colors": ["#34495e", "#1abc9c"],
        "sizes": ["One Size"]
    },
    {
        "id": "sai0012",
        "name": "Herschel Leather Belt",
        "price": 63.15,
        "image": "images/product-12.jpg",
        "category": "men",
        "description": "Classic leather belt with a modern buckle design. A must-have accessory for any wardrobe.",
        "tags": ["Fashion", "Belt"],
        "colors": ["#7f8c8d", "#2c3e50"],
        "sizes": ["S", "M", "L"]
    },
    {
        "id": "sai0013",
        "name": "T-Shirt with Sleeve",
        "price": 18.49,
        "image": "images/product-13.jpg",
        "category": "women",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Shirt"],
        "colors": ["#9b59b6", "#ecf0f1"],
        "sizes": ["S", "M", "L"]
    },
    {
        "id": "sai0014",
        "name": "Pretty Little Thing",
        "price": 54.79,
        "image": "images/product-14.jpg",
        "category": "women",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Trendy"],
        "colors": ["#f1c40f", "#2ecc71"],
        "sizes": ["S", "M"]
    },
    {
        "id": "sai0015",
        "name": "Mini Silver Mesh Watch",
        "price": 86.85,
        "image": "images/product-15.jpg",
        "category": "watches",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Watch"],
        "colors": ["#bdc3c7", "#f1c40f"],
        "sizes": ["Adjustable"]
    },
    {
        "id": "sai0016",
        "name": "Square Neck Back",
        "price": 29.64,
        "image": "images/product-16.jpg",
        "category": "women",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Top"],
        "colors": ["#3498db", "#e74c3c"],
        "sizes": ["S", "M", "L"]
    },
    {
        "id": "sai_f_002",
        "name": "High-Performance Running Shoes",
        "price": 95.00,
        "image": "images/products/footwear_running_shoes_front.png",
        "category": "shoes",
        "description": "Professional-grade running shoes with advanced cushioning technology. Features breathable mesh upper and responsive midsole for maximum performance.",
        "tags": ["shoes", "running", "athletic", "performance"],
        "colors": ["#00BFFF", "#FF8C00", "#000000"],
        "sizes": ["7", "8", "9", "10", "11", "12"]
    },
    {
        "id": "sai_f_003",
        "name": "Classic Black Stiletto Heels",
        "price": 110.00,
        "image": "images/products/footwear_stiletto_heels_front.png",
        "category": "shoes",
        "description": "Timeless black patent leather stiletto heels. Features a pointed toe and ultra-high heel for elegant evening wear. Red sole accent.",
        "tags": ["heels", "stiletto", "formal", "luxury"],
        "colors": ["#000000", "#8B0000"],
        "sizes": ["6", "7", "8", "9", "10"]
    },
    {
        "id": "sai_f_004",
        "name": "Casual Canvas Slip-Ons",
        "price": 48.00,
        "image": "images/products/footwear_canvas_slip_ons_front.png",
        "category": "shoes",
        "description": "Comfortable canvas slip-on shoes perfect for everyday wear. Features elastic side panels for easy on/off and a cushioned insole.",
        "tags": ["shoes", "casual", "canvas", "slip-on"],
        "colors": ["#D3D3D3", "#000000", "#F5F5DC"],
        "sizes": ["7", "8", "9", "10", "11", "12"]
    },
    {
        "id": "sai_f_005",
        "name": "Rugged Outdoor Hiking Boots",
        "price": 135.00,
        "image": "images/products/footwear_hiking_boots_front.png",
        "category": "shoes",
        "description": "Durable hiking boots built for tough terrain. Features waterproof leather construction, ankle support, and aggressive tread pattern for superior grip.",
        "tags": ["boots", "hiking", "outdoor", "waterproof"],
        "colors": ["#D2691E", "#8B4513"],
        "sizes": ["7", "8", "9", "10", "11", "12", "13"]
    },
    // Men's Clothing
    {
        "id": "sai1001",
        "name": "Slim Fit Oxford Shirt",
        "price": 59.99,
        "image": "images/products/mens_oxford_shirt.png",
        "category": "men",
        "description": "Premium white Oxford shirt in slim fit. Crisp cotton fabric with button-down collar. Perfect for business or smart casual occasions.",
        "tags": ["formal", "shirt", "oxford", "cotton"],
        "colors": ["#FFFFFF", "#87CEEB", "#FFB6C1"],
        "sizes": ["S", "M", "L", "XL", "XXL"]
    },
    {
        "id": "sai1002",
        "name": "Classic Polo Shirt",
        "price": 45.00,
        "image": "images/products/mens_polo.png",
        "category": "men",
        "description": "Premium navy blue polo with pique cotton texture. Embroidered logo detail. Timeless style for any occasion.",
        "tags": ["casual", "polo", "cotton", "classic"],
        "colors": ["#000080", "#DC143C", "#228B22"],
        "sizes": ["S", "M", "L", "XL"]
    },
    {
        "id": "sai1003",
        "name": "Classic Denim Jacket",
        "price": 89.99,
        "image": "images/products/mens_denim_jacket.png",
        "category": "men",
        "description": "Authentic denim jacket in medium blue wash. Metal buttons and timeless design. Essential layering piece for any wardrobe.",
        "tags": ["denim", "jacket", "casual", "classic"],
        "colors": ["#4169E1", "#000000", "#87CEEB"],
        "sizes": ["S", "M", "L", "XL"]
    },
    {
        "id": "sai1004",
        "name": "Premium Wool Blazer",
        "price": 189.00,
        "image": "images/products/mens_wool_blazer.png",
        "category": "men",
        "description": "Sophisticated charcoal gray wool blazer with two-button design. Notch lapel and fine tailoring for a refined look.",
        "tags": ["formal", "blazer", "wool", "tailored"],
        "colors": ["#2F4F4F", "#000080", "#2F2F2F"],
        "sizes": ["38", "40", "42", "44", "46"]
    },
    {
        "id": "sai1005",
        "name": "Slim Fit Chinos",
        "price": 65.00,
        "image": "images/products/mens_chinos.png",
        "category": "men",
        "description": "Modern slim fit chinos in classic khaki. Premium cotton twill with stretch for comfort. Versatile everyday essential.",
        "tags": ["pants", "chinos", "slim-fit", "cotton"],
        "colors": ["#D2B48C", "#2F4F4F", "#000080"],
        "sizes": ["28", "30", "32", "34", "36"]
    },
    {
        "id": "sai1006",
        "name": "Casual Linen Shirt",
        "price": 55.00,
        "image": "images/products/mens_linen_shirt.png",
        "category": "men",
        "description": "Light blue linen shirt with relaxed fit. Natural breathable fabric perfect for warm weather. Button-down collar styling.",
        "tags": ["casual", "linen", "summer", "breathable"],
        "colors": ["#87CEEB", "#FFFFFF", "#F5F5DC"],
        "sizes": ["S", "M", "L", "XL"]
    },
    {
        "id": "sai1007",
        "name": "Athletic Hoodie",
        "price": 69.99,
        "image": "images/products/mens_hoodie.png",
        "category": "men",
        "description": "Premium heather gray athletic hoodie. Soft fleece interior with kangaroo pocket. Perfect for workouts or casual wear.",
        "tags": ["athletic", "hoodie", "casual", "fleece"],
        "colors": ["#808080", "#000000", "#2F4F4F"],
        "sizes": ["S", "M", "L", "XL", "XXL"]
    },
    {
        "id": "sai1008",
        "name": "V-Neck Cashmere Sweater",
        "price": 149.00,
        "image": "images/products/mens_cashmere_sweater.png",
        "category": "men",
        "description": "Luxurious burgundy V-neck cashmere sweater. Fine knit texture with elegant finish. The ultimate in comfort and style.",
        "tags": ["luxury", "cashmere", "knitwear", "winter"],
        "colors": ["#800020", "#2F4F4F", "#000080"],
        "sizes": ["S", "M", "L", "XL"]
    },
    {
        "id": "sai1009",
        "name": "Tailored Dress Pants",
        "price": 95.00,
        "image": "images/products/mens_dress_pants.png",
        "category": "men",
        "description": "Elegant charcoal gray dress pants in wool blend. Tailored fit with pressed crease. Essential for the modern professional.",
        "tags": ["formal", "pants", "tailored", "wool"],
        "colors": ["#2F4F4F", "#000000", "#2F2F2F"],
        "sizes": ["28", "30", "32", "34", "36", "38"]
    },
    {
        "id": "sai1010",
        "name": "Bomber Jacket",
        "price": 125.00,
        "image": "images/products/mens_bomber_jacket.png",
        "category": "men",
        "description": "Classic olive green bomber jacket. Ribbed cuffs and hem with front zip. Iconic military-inspired streetwear style.",
        "tags": ["jacket", "bomber", "streetwear", "military"],
        "colors": ["#556B2F", "#000000", "#2F4F4F"],
        "sizes": ["S", "M", "L", "XL"]
    },
    // Women's Clothing
    {
        "id": "sai2001",
        "name": "Floral Midi Dress",
        "price": 85.00,
        "image": "images/products/womens_floral_dress.png",
        "category": "women",
        "description": "Elegant pink floral midi dress with flutter sleeves. Soft flowing fabric with romantic rose pattern. Perfect for special occasions.",
        "tags": ["dress", "floral", "romantic", "midi"],
        "colors": ["#FFB6C1", "#FFFFFF", "#98FB98"],
        "sizes": ["XS", "S", "M", "L"]
    },
    {
        "id": "sai2002",
        "name": "Silk Blouse",
        "price": 120.00,
        "image": "images/products/womens_silk_blouse.png",
        "category": "women",
        "description": "Luxurious ivory silk blouse with delicate pearl buttons. Soft drape and elegant collar. Timeless sophistication.",
        "tags": ["silk", "blouse", "luxury", "elegant"],
        "colors": ["#FFFFF0", "#000000", "#FFB6C1"],
        "sizes": ["XS", "S", "M", "L", "XL"]
    },
    {
        "id": "sai2003",
        "name": "High-Waist Skinny Jeans",
        "price": 79.00,
        "image": "images/products/womens_skinny_jeans.png",
        "category": "women",
        "description": "Dark indigo skinny jeans with high waist fit. Premium stretch denim for comfort. Flattering silhouette for all body types.",
        "tags": ["denim", "jeans", "skinny", "stretch"],
        "colors": ["#00008B", "#000000", "#87CEEB"],
        "sizes": ["24", "26", "28", "30", "32"]
    },
    {
        "id": "sai2004",
        "name": "Cashmere Cardigan",
        "price": 165.00,
        "image": "images/products/womens_cardigan.png",
        "category": "women",
        "description": "Soft pink cashmere cardigan with button front. Ultra-soft fine knit for luxurious comfort. Perfect layering piece.",
        "tags": ["cashmere", "cardigan", "knitwear", "luxury"],
        "colors": ["#FFB6C1", "#F5F5DC", "#808080"],
        "sizes": ["XS", "S", "M", "L"]
    },
    {
        "id": "sai2005",
        "name": "Pleated Maxi Skirt",
        "price": 75.00,
        "image": "images/products/womens_pleated_skirt.png",
        "category": "women",
        "description": "Champagne gold pleated maxi skirt. Flowing fabric with elegant movement. Statement piece for sophisticated style.",
        "tags": ["skirt", "pleated", "maxi", "elegant"],
        "colors": ["#D4AF37", "#C0C0C0", "#000000"],
        "sizes": ["XS", "S", "M", "L"]
    },
    {
        "id": "sai2006",
        "name": "Cropped Blazer",
        "price": 135.00,
        "image": "images/products/womens_cropped_blazer.png",
        "category": "women",
        "description": "Chic black cropped blazer with gold buttons. Fitted design with double-breasted styling. Power dressing essential.",
        "tags": ["blazer", "cropped", "formal", "power-dressing"],
        "colors": ["#000000", "#FFFFFF", "#2F4F4F"],
        "sizes": ["XS", "S", "M", "L", "XL"]
    },
    {
        "id": "sai2007",
        "name": "Off-Shoulder Top",
        "price": 45.00,
        "image": "images/products/womens_off_shoulder_top.png",
        "category": "women",
        "description": "White cotton off-shoulder top with ruffle details. Feminine and fresh summer essential. Lightweight and breathable.",
        "tags": ["top", "summer", "cotton", "feminine"],
        "colors": ["#FFFFFF", "#87CEEB", "#FFB6C1"],
        "sizes": ["XS", "S", "M", "L"]
    },
    {
        "id": "sai2008",
        "name": "Wrap Dress",
        "price": 95.00,
        "image": "images/products/womens_wrap_dress.png",
        "category": "women",
        "description": "Navy blue wrap dress with subtle floral print. V-neckline with tie waist. Flattering fit for any occasion.",
        "tags": ["dress", "wrap", "elegant", "versatile"],
        "colors": ["#000080", "#000000", "#800020"],
        "sizes": ["XS", "S", "M", "L", "XL"]
    },
    // Footwear
    {
        "id": "sai3001",
        "name": "Classic White Sneakers",
        "price": 129.00,
        "image": "images/products/white_sneakers.png",
        "category": "shoes",
        "description": "Premium white leather sneakers with minimalist design. Clean modern style with comfortable cushioned sole. Wardrobe essential.",
        "tags": ["sneakers", "leather", "minimalist", "classic"],
        "colors": ["#FFFFFF", "#000000", "#F5F5DC"],
        "sizes": ["6", "7", "8", "9", "10", "11", "12"]
    },
    // Bags & Accessories
    {
        "id": "sai4001",
        "name": "Leather Tote Bag",
        "price": 195.00,
        "image": "images/products/leather_tote_bag.png",
        "category": "bag",
        "description": "Premium brown leather tote bag with gold hardware. Structured design with elegant handles. Sophisticated everyday luxury.",
        "tags": ["bag", "tote", "leather", "luxury"],
        "colors": ["#8B4513", "#000000", "#D2B48C"],
        "sizes": ["One Size"]
    },
    // Watches
    {
        "id": "sai5001",
        "name": "Minimalist Leather Watch",
        "price": 159.00,
        "image": "images/products/minimalist_watch.png",
        "category": "watches",
        "description": "Elegant minimalist watch with brown leather strap. White dial with rose gold case. Timeless design for everyday wear.",
        "tags": ["watch", "minimalist", "leather", "elegant"],
        "colors": ["#8B4513", "#000000", "#C0C0C0"],
        "sizes": ["One Size"]
    }
];
