export const products = [
    {
        "id": "sai0001",
        "name": "Esprit Ruffle Shirt",
        "price": 16.64,
        "image": "images/product-01.jpg",
        "category": "women",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Shirt"],
        "colors": ["#717fe0", "#e67e22", "#2ecc71"],
        "sizes": ["S", "M", "L", "XL"]
    },
    {
        "id": "sai0002",
        "name": "Herschel supply",
        "price": 35.31,
        "image": "images/product-02.jpg",
        "category": "bag",
        "description": "This premium bag blends functionality with minimalist design. Perfect for daily use or light travel.",
        "tags": ["Fashion", "Bag"],
        "colors": ["#333333", "#ffffff", "#f1c40f"],
        "sizes": ["One Size"]
    },
    {
        "id": "sai0003",
        "name": "Only Check Trouser",
        "price": 25.50,
        "image": "images/product-03.jpg",
        "category": "men",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Denim"],
        "colors": ["#2c3e50", "#95a5a6"],
        "sizes": ["M", "L", "XL"]
    },
    {
        "id": "sai0004",
        "name": "Classic Trench Coat",
        "price": 75.00,
        "image": "images/product-04.jpg",
        "category": "women",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Coat"],
        "colors": ["#d35400", "#2c3e50"],
        "sizes": ["S", "M", "L"]
    },
    {
        "id": "sai0005",
        "name": "Front Pocket Jumper",
        "price": 34.75,
        "image": "images/product-05.jpg",
        "category": "women",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Jumper"],
        "colors": ["#9b59b6", "#34495e"],
        "sizes": ["S", "M", "L"]
    },
    {
        "id": "sai0006",
        "name": "Vintage Inspired Classic",
        "price": 93.20,
        "image": "images/product-06.jpg",
        "category": "watches",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Watch"],
        "colors": ["#f1c40f", "#bdc3c7"],
        "sizes": ["Adjustable"]
    },
    {
        "id": "sai0007",
        "name": "Shirt in Stretch Cotton",
        "price": 52.66,
        "image": "images/product-07.jpg",
        "category": "women",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Shirt"],
        "colors": ["#ffffff", "#3498db"],
        "sizes": ["S", "M", "L", "XL"]
    },
    {
        "id": "sai0008",
        "name": "Pieces Metallic Printed",
        "price": 18.96,
        "image": "images/product-08.jpg",
        "category": "women",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Qt", "Fashion"],
        "colors": ["#e74c3c", "#f39c12"],
        "sizes": ["S", "M"]
    },
    {
        "id": "sai0009",
        "name": "Converse All Star Hi Plimsolls",
        "price": 75.00,
        "image": "images/product-09.jpg",
        "category": "shoes",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Shoes"],
        "colors": ["#ffffff", "#e74c3c", "#333333"],
        "sizes": ["38", "39", "40", "41", "42"]
    },
    {
        "id": "sai0010",
        "name": "Femme T-Shirt In Stripe",
        "price": 25.85,
        "image": "images/product-10.jpg",
        "category": "women",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Shirt"],
        "colors": ["#3498db", "#bdc3c7"],
        "sizes": ["S", "M", "L"]
    },
    {
        "id": "sai0011",
        "name": "Herschel Travel Backpack",
        "price": 63.16,
        "image": "images/product-11.jpg",
        "category": "bag",
        "description": "A spacious and durable backpack for all your travel needs. Featuring multiple compartments and ergonomic straps.",
        "tags": ["Fashion", "Bag"],
        "colors": ["#34495e", "#1abc9c"],
        "sizes": ["One Size"]
    },
    {
        "id": "sai0012",
        "name": "Herschel Leather Belt",
        "price": 63.15,
        "image": "images/product-12.jpg",
        "category": "men",
        "description": "Classic leather belt with a modern buckle design. A must-have accessory for any wardrobe.",
        "tags": ["Fashion", "Belt"],
        "colors": ["#7f8c8d", "#2c3e50"],
        "sizes": ["S", "M", "L"]
    },
    {
        "id": "sai0013",
        "name": "T-Shirt with Sleeve",
        "price": 18.49,
        "image": "images/product-13.jpg",
        "category": "women",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Shirt"],
        "colors": ["#9b59b6", "#ecf0f1"],
        "sizes": ["S", "M", "L"]
    },
    {
        "id": "sai0014",
        "name": "Pretty Little Thing",
        "price": 54.79,
        "image": "images/product-14.jpg",
        "category": "women",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Trendy"],
        "colors": ["#f1c40f", "#2ecc71"],
        "sizes": ["S", "M"]
    },
    {
        "id": "sai0015",
        "name": "Mini Silver Mesh Watch",
        "price": 86.85,
        "image": "images/product-15.jpg",
        "category": "watches",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Watch"],
        "colors": ["#bdc3c7", "#f1c40f"],
        "sizes": ["Adjustable"]
    },
    {
        "id": "sai0016",
        "name": "Square Neck Back",
        "price": 29.64,
        "image": "images/product-16.jpg",
        "category": "women",
        "description": "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
        "tags": ["Fashion", "Top"],
        "colors": ["#3498db", "#e74c3c"],
        "sizes": ["S", "M", "L"]
    },
    {
        "id": "sai_f_002",
        "name": "High-Performance Running Shoes",
        "price": 95.00,
        "image": "images/products/footwear_running_shoes_front.png",
        "category": "shoes",
        "description": "Professional-grade running shoes with advanced cushioning technology. Features breathable mesh upper and responsive midsole for maximum performance.",
        "tags": ["shoes", "running", "athletic", "performance"],
        "colors": ["#00BFFF", "#FF8C00", "#000000"],
        "sizes": ["7", "8", "9", "10", "11", "12"]
    },
    {
        "id": "sai_f_003",
        "name": "Classic Black Stiletto Heels",
        "price": 110.00,
        "image": "images/products/footwear_stiletto_heels_front.png",
        "category": "shoes",
        "description": "Timeless black patent leather stiletto heels. Features a pointed toe and ultra-high heel for elegant evening wear. Red sole accent.",
        "tags": ["heels", "stiletto", "formal", "luxury"],
        "colors": ["#000000", "#8B0000"],
        "sizes": ["6", "7", "8", "9", "10"]
    },
    {
        "id": "sai_f_004",
        "name": "Casual Canvas Slip-Ons",
        "price": 48.00,
        "image": "images/products/footwear_canvas_slip_ons_front.png",
        "category": "shoes",
        "description": "Comfortable canvas slip-on shoes perfect for everyday wear. Features elastic side panels for easy on/off and a cushioned insole.",
        "tags": ["shoes", "casual", "canvas", "slip-on"],
        "colors": ["#D3D3D3", "#000000", "#F5F5DC"],
        "sizes": ["7", "8", "9", "10", "11", "12"]
    },
    {
        "id": "sai_f_005",
        "name": "Rugged Outdoor Hiking Boots",
        "price": 135.00,
        "image": "images/products/footwear_hiking_boots_front.png",
        "category": "shoes",
        "description": "Durable hiking boots built for tough terrain. Features waterproof leather construction, ankle support, and aggressive tread pattern for superior grip.",
        "tags": ["boots", "hiking", "outdoor", "waterproof"],
        "colors": ["#D2691E", "#8B4513"],
        "sizes": ["7", "8", "9", "10", "11", "12", "13"]
    }
];
